/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import {Route as rootRoute} from './routes/__root';
import {Route as AnnouncementImport} from './routes/announcement';
import {Route as IndexImport} from './routes/index';

// Create/Update Routes

const AnnouncementRoute = AnnouncementImport.update({
    id: '/announcement',
    path: '/announcement',
    getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
    interface FileRoutesByPath {
        '/': {
            id: '/';
            path: '/';
            fullPath: '/';
            preLoaderRoute: typeof IndexImport;
            parentRoute: typeof rootRoute;
        };
        '/announcement': {
            id: '/announcement';
            path: '/announcement';
            fullPath: '/announcement';
            preLoaderRoute: typeof AnnouncementImport;
            parentRoute: typeof rootRoute;
        };
    }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
    '/': typeof IndexRoute;
    '/announcement': typeof AnnouncementRoute;
}

export interface FileRoutesByTo {
    '/': typeof IndexRoute;
    '/announcement': typeof AnnouncementRoute;
}

export interface FileRoutesById {
    __root__: typeof rootRoute;
    '/': typeof IndexRoute;
    '/announcement': typeof AnnouncementRoute;
}

export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath;
    fullPaths: '/' | '/announcement';
    fileRoutesByTo: FileRoutesByTo;
    to: '/' | '/announcement';
    id: '__root__' | '/' | '/announcement';
    fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
    IndexRoute: typeof IndexRoute;
    AnnouncementRoute: typeof AnnouncementRoute;
}

const rootRouteChildren: RootRouteChildren = {
    IndexRoute: IndexRoute,
    AnnouncementRoute: AnnouncementRoute,
};

export const routeTree = rootRoute
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/announcement"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/announcement": {
      "filePath": "announcement.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
